# Site settings
title: Outdoor Executives
description: 'Paving the way for personal and professional success' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://the-mvm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/OutdoorExecutives_Logo.png"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Outdoor Executives # add your name
author-pic: Myself_Neon_grey.jpg
about-author: While workig in large corporations for over 20 years I noticed that many people were not reaching their potential. They were not doing what they new they could do. This lead to self disappointment,  lack of progression and in the worst case mental and physical breakdown. I have successfull used experiences in the outdoors and well know personal development techniques to find and live my lifes purpose. I want to help you do the same.

# Contact links
email: info@outdoorexecutives.com # Add your Email address
phone: # Add your Phone number
website: https://amaynez.github.io # Add your website
linkedin: amaynez # Add your Linkedin handle
github: amaynez # Add your Github handle
twitter: '@MvmThe' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
destination: public

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]